title: "inze.ph"
url: https://inze.ph
logo: /assets/images/logo.png

include:
  - .well-known

markdown: kramdown

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

collections:
  talks:
    output: true
  projects:
    output: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      permalink: "/writing/:slug"
      # filtered in writing.md
      # lets me set listed: false to unlist a post that i might want in
      # semi-draft or semi-private mode
      listed: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      permalink: "/speaking/:slug"
  # _projects
  - scope:
      path: ""
      type: projects
    values:
      layout: project
      permalink: "/projects/:slug"

kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
