server {
    listen 80;
    server_name phinze.com;
    return 301 https://inze.ph$request_uri;
}

server {
    listen 80;
    server_name inze.ph;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ $uri.html =404;
    }

    error_page 404 /404.html;
}
